// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_StD0Y7lBdMmjup9rE-buV5pBA9wUQkM',
    appId: '1:1027553989259:web:2b0db592d67cb7b46e7a8e',
    messagingSenderId: '1027553989259',
    projectId: 'firegp2-27d23',
    authDomain: 'firegp2-27d23.firebaseapp.com',
    storageBucket: 'firegp2-27d23.firebasestorage.app',
    measurementId: 'G-LYLJZ5RK4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClo7lfEGZSxzVkO8ABcMANaB61LL51MjQ',
    appId: '1:28515859742:android:805ae46a3782bab6d61d0f',
    messagingSenderId: '28515859742',
    projectId: 'torbetnah',
    storageBucket: 'torbetnah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfBVcg7FnK_nMFfYspq2b_SXzZMF4-2co',
    appId: '1:28515859742:ios:d8c44749fafe5cf8d61d0f',
    messagingSenderId: '28515859742',
    projectId: 'torbetnah',
    storageBucket: 'torbetnah.firebasestorage.app',
    iosBundleId: 'com.example.gp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFFj9uy7ZAp-0acbZ22_Pnnnv8aaQc9xg',
    appId: '1:1027553989259:ios:624382b7f1abd3e86e7a8e',
    messagingSenderId: '1027553989259',
    projectId: 'firegp2-27d23',
    storageBucket: 'firegp2-27d23.firebasestorage.app',
    iosBundleId: 'com.example.gp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_StD0Y7lBdMmjup9rE-buV5pBA9wUQkM',
    appId: '1:1027553989259:web:834905d26e3770136e7a8e',
    messagingSenderId: '1027553989259',
    projectId: 'firegp2-27d23',
    authDomain: 'firegp2-27d23.firebaseapp.com',
    storageBucket: 'firegp2-27d23.firebasestorage.app',
    measurementId: 'G-NCW499MD9Z',
  );
}